spring:
  datasource:
    url: jdbc:h2:mem:db_credit_application_system
    username: lira
    password:
  jpa:
    show-sql: true
#    hibernate:
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
